/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jcommerceVIEW;

import br.com.jcommerceCTR.EstadoCTR;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno(a)
 */
public class PesquisarEstadoVIEW extends javax.swing.JFrame {

    ResultSet rsRegistros;
    String codEstado;
    public CadastroEstadoVIEW objetocadastro;
    /**
     * Creates new form PesquisarEstadoVIEW
     */
    public PesquisarEstadoVIEW() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPesquisaEstado = new javax.swing.JTextField();
        pesquisarEstado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Pesquisa:");

        pesquisarEstado.setText("Pesquisar");
        pesquisarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarEstadoActionPerformed(evt);
            }
        });

        tblEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstadoMouseClicked(evt);
            }
        });
        tblEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblEstadoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblEstado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarEstado))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarEstadoActionPerformed
        // TODO add your handling code here:
        acaoBtnBuscar();
    }//GEN-LAST:event_pesquisarEstadoActionPerformed

    private void tblEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblEstadoKeyPressed
        // TODO add your handling code here:
        int linha = tblEstado.getSelectedRow();
        
        objetocadastro.txtCod.setText(String.valueOf(tblEstado.getValueAt(linha, 0)));
        objetocadastro.txtEstado.setText((String)tblEstado.getValueAt(linha, 1));
        objetocadastro.txtSigla.setText((String)tblEstado.getValueAt(linha, 2));
        
        dispose();
    }//GEN-LAST:event_tblEstadoKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtPesquisaEstado.grabFocus();
    }//GEN-LAST:event_formWindowOpened

    private void tblEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstadoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) 
        {
            int linha = tblEstado.getSelectedRow();
        
        objetocadastro.txtCod.setText(String.valueOf(tblEstado.getValueAt(linha, 0)));
        objetocadastro.txtEstado.setText((String)tblEstado.getValueAt(linha, 1));
        objetocadastro.txtSigla.setText((String)tblEstado.getValueAt(linha, 2));
        
        dispose();
        }
    }//GEN-LAST:event_tblEstadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarEstadoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarEstadoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarEstadoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarEstadoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarEstadoVIEW().setVisible(true);
            }
        });
    }
    
    private void preencheTabela()
    {
        try
        {
            EstadoCTR estadoCTR = new EstadoCTR();
            ResultSet rsEstadoTabela = estadoCTR.listaEstado();
            
            String[] todos = {"Código", "Nome Estado", "Sigla Estado"};
            String[][] linhas = {};
            
            DefaultTableModel tableModel = new DefaultTableModel(linhas, todos){
                
                public boolean isCellEditTable(int rowIndex, int mColIndex){ 
                    return false;
                }
            };
            
            Vector<Vector> dados = new Vector<>();
            
            while(rsEstadoTabela.next()){
                
                Vector regVetor = new Vector();
                regVetor.add(rsEstadoTabela.getInt("codestado"));
                regVetor.add(rsEstadoTabela.getString("nomeestado"));
                regVetor.add(rsEstadoTabela.getString("siglaestado"));
                
                dados.add(regVetor);
                tableModel.addRow(regVetor);
            }
            
            tblEstado.setModel(tableModel);
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void pegaValorSelecionado() 
    {
        codEstado = String.valueOf(tblEstado.getValueAt(tblEstado.getSelectedRow(), 0));
        this.dispose();
    }
    
    public void buscaEstado() 
    {
        EstadoCTR estadoCTR = new EstadoCTR();
        rsRegistros = estadoCTR.pesquisarEstado(txtPesquisaEstado.getText());
        preencheTabela();
    }
    
    public void acaoBtnBuscar()
    {
        buscaEstado();
        if (tblEstado.getRowCount() > 0) 
        {
            tblEstado.changeSelection(0, 0, false, false);
        }
        tblEstado.grabFocus();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pesquisarEstado;
    private javax.swing.JTable tblEstado;
    private javax.swing.JTextField txtPesquisaEstado;
    // End of variables declaration//GEN-END:variables
}
